FROM python:3.11-slim

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        gcc \
        libpcsclite-dev \
        libusb-1.0-0 \
        pcscd \
        pcsc-tools \
    && rm -rf /var/lib/apt/lists/*

COPY backend/requirements.txt ./backend/requirements.txt

RUN pip install --no-cache-dir -r ./backend/requirements.txt

COPY backend ./backend

CMD ["python", "backend/nfc_reader.py"]
