services:
  tapp-app:
    build: .
    container_name: tapp-local
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - tapp-db
  
  tapp-db:
    image: postgres:15
    container_name: tapp-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6767
      POSTGRES_DB: tapp_battery
    ports:
      - "5432:5432"
    volumes:
      - tapp-db-data:/var/lib/postgresql/data
  
volumes:
  tapp-db-data: