services:
  tapp-db:
    image: postgres:15
    container_name: tapp-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_HOST}
    ports:
      - "5432:5432"
    volumes:
      - tapp-db-data:/var/lib/postgresql/data
  
volumes:
  tapp-db-data: